[metadata]
id = "flask-postgresql"
version = "1.0"
release = 4
title = "Flask + Postgres demo app"
author = "Nua developers"
tagline = "postgres docker configured via orchestrator"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "plugin", "PostgreSQL", "docker", "psycopg2"]

[build]
license = "MIT"
test = "python -c 'import flask_app'"

[run]
start = ["init-db", "gunicorn --workers 2 -b :5000 flask_app.app:app"]

[env]
DB_HOST = { from="database", key="hostname" }
DB_PORT = { from="database", key="POSTGRES_PORT" }
DB_NAME = { from="database", key="POSTGRES_DB" }
DB_USERNAME = { from="database", key="POSTGRES_USER" }
DB_PASSWORD = { from="database", key="POSTGRES_PASSWORD" }

[docker]
restart_policy.name = "always"

[port.web]
# publication port of the app inside the container
container = 5000

[[provider]]
# declaration of the required image for the provider, here the official Postgres
# Docker image
name = "database"
plugin-name = "postgres"
plugin-version = ">=14, <15"
