[metadata]
id = "no-public-port"
version = "1.0"
release = 3
title = "Nua test server 2 ports, not published outside."
author = "Jerome Dumonteil <jd@abilian.com>"
tagline = "Nua test server 2 ports"
website = "https://nua.rocks/"
tags = ["test", "noweb"]
license = "MIT"

[build]
test = "python -c 'import echos'"

[run]
start = "python -c 'from echos.echo_server import echos; echos(8764, 8765)'"

[port.one]
container = 8764
proxy = 8764

[port.two]
container = 8765
proxy = 8765
