[metadata]
id = "dolibarr-mariadb"
version = "16.0"
release = 12
title = "Dolibarr (for mariadb), based on tuxgazy dockerfile"
author = "Dolibarr developers"
tagline = "Nua test with Dolibarr"
website = "https://nua.rocks/"
tags = ["test", "php", "web", "Dolibarr"]
licence = "GPLv3"

[build]
manifest = ["nua"]
default_files = false
# test = "test -f /nua/metadata/nua-config.json" -> default test

[[assign]]
key = "DOLI_DB_HOST"
property = "database.hostname"

[[assign]]
key = "DOLI_DB_USER"
property = "database.MARIADB_USER"

[[assign]]
key = "DOLI_DB_PASSWORD"
property = "database.MARIADB_PASSWORD"

[[assign]]
key = "DOLI_DB_NAME"
property = "database.MARIADB_DATABASE"

[[assign]]
key = "DOLI_ADMIN_PASSWORD"
random_str = true
display = true

[env]
DOLI_ADMIN_LOGIN = "admin"
DOLI_URL_ROOT = 'http://0.0.0.0'
PHP_INI_DATE_TIMEZONE = 'Europe/Paris'
# DOLI_DB_HOST_PORT = "3306"

[port.web]
container = 80

[healthcheck]
command = "true"  # shell true -> no command, always ok, for test
start-period = 900
interval = 30
timeout = 30
retries = 3

[[volume]]
# declare a local volume for plublic uploads
# type = "bind"
type = "volume"
# Name of the driver used to create the volume: (for type == "volume")
driver = "local"
# Mount source (e.g. a volume name or a host path):
prefix = "dolibarr_custom"
# Container path:
target = "/var/www/html/custom"

[[volume]]
# declare a local volume for plublic uploads
# type = "bind"
type = "volume"
# Name of the driver used to create the volume: (for type == "volume")
driver = "local"
# Mount source (e.g. a volume name or a host path):
prefix = "dolibarr_documents"
# Container path:
target = "/var/www/documents"


[[resource]]
# A resource is another container required by the main app container, its
# configuration is described below, under the key of name of the resource. Several
# resources can be declared. The resource host will appear in the local network
# with a hostname equal to the container name.

# Declaration of the required image for the resource, here the official Mariadb.
name = "database"
type = "mariadb"
version = ">=10.6, <10.7"
create_user = true
create_db = true  # Dolibarr will create it ?
