[metadata]
id = "dolibarr-mariadb-wrap"
version = "16.0.4"
release = 7
title = "Dolibarr (on mariadb), wrap build based on tuxgazy Docker image"
author = "Dolibarr developers"
tagline = "Open Source ERP & CRM for business"
website = "https://www.dolibarr.org/"
tags = ["test", "php", "web", "Dolibarr"]

[build]
license = "GPLv3"
# here the wrapped Docker declaration:
base-image = "tuxgasy/dolibarr:{version}"
# base-image statement permit auto-detection of "wrap" method:
# method = "wrap"

[env]
DOLI_DB_HOST = { from="database", key="hostname" }
DOLI_DB_USER = { from="database", key="MARIADB_USER" }
DOLI_DB_PASSWORD = { from="database", key="MARIADB_PASSWORD" }
DOLI_DB_NAME = { from="database", key="MARIADB_DATABASE" }
DOLI_ADMIN_PASSWORD = { random='true' }

DOLI_ADMIN_LOGIN = "admin"
DOLI_URL_ROOT = 'http://0.0.0.0'
PHP_INI_DATE_TIMEZONE = 'Europe/Paris'
# DOLI_DB_HOST_PORT = "3306"

[port.web]
container = 80

[healthcheck]
command = "true"  # shell true -> no command, always ok, for test
start-period = 900
interval = 30
timeout = 30
retries = 3

[[volume]]
name = "dolibarr_custom"
# Container path:
target = "/var/www/html/custom"

[[volume]]
name = "dolibarr_documents"
# Container path:
target = "/var/www/documents"

[backup]
method = "tgz_volumes"
frequency = "24h"
options = { destination = "local" }


[[provider]]
# A provider is another container required by the main app container, its
# configuration is described below, under the key of name of the provider. Several
# providers can be declared. The provider host will appear in the local network
# with a hostname equal to the container name.

# Declaration of the required image for the provider, here the official Mariadb.
name = "database"
plugin-name = "mariadb"
plugin-version = ">=10.6, <10.7"
# create_user = true -> the default
# create_db = true   -> the default

[provider.backup]
method = "mysqldump"
options = { destination = "local" }
