[metadata]
id = "flask-sub-folder"
version = "1.2"
release = 2
title = "Flask test nua in sub folder"
author = "Nua testers"
tagline = "Nua test with Flask - sub"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
license = "MIT"

[build]
test = "python -c 'import flask_sub_folder'"

[docker]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
