[metadata]
id = "flask-sqla-sqlite-bind"
version = "1.0"
release = 6
title = "Nua test with sqlalchemy, sqlite on bind volume"
author = "Nua testers"
tagline = "Nua test with sqlalchemy, sqlite on bind volume"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "flask", "plugin", "sqlite", "sqlalchemy"]

[build]
license = "MIT"
test = "python -c 'import flask_sqla_sqlite_bind'"

[env]
# parameters passed as a dict to docker run: environment dict
DB_FOLDER = "/nua/app/dbs"
DB_NAME = "student_test.db"

[docker]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 5000

[[volume]]
type = "directory"
name = "/var/tmp"
target = "/nua/app/dbs"
