[metadata]
id = "galene"
version = "0.6.2"
release = 6
title = "Galène videoconference server "
author = "Galene authors"
tagline = "Galène videoconference server"
website = "https://galene.org/"
tags = ["golang", "visio"]

[build]
license = "MIT"
git-url = "https://github.com/jech/galene.git"
git-branch = "galene-0.6-branch"
packages = ['golang-go', 'git']  # go modules need git for VCS version
build = [
    "CGO_ENABLED=0 go build -ldflags='-s -w'",
    "cp galene /nua/app",
    "cp LICENCE /nua/app",
    "cp -a static /nua/app",
    "mkdir /nua/app/groups",
    "mkdir /nua/app/data"
]
test = "test -f /nua/app/galene"

[run]
start = """\
/nua/app/galene \
-insecure \
-http 127.0.0.1:${LISTEN_PORT} \
-turn :${TURN_PORT} \
-udp-range 49152-65535 \
-groups /nua/app/groups \
-data /nua/app/data"""
# -recordings __DATA_DIR__/recordings  \

[env]
LISTEN_PORT = 8443
TURN_PORT = 1194
GALENE_ADMIN = "admin"
GALENE_ADM_PWD = { random='true', length=24 }
GALENE_OPERATOR = "galene"
GALENE_OP_PWD = { random='true', length=24 }
DOMAIN = { key="domain" }
# REALM = { key="domain_realm" }
# EXTERNAL_IP = { external_ip=true }
GROUP_PUBLIC = "true"
GROUP_DISPLAYNAME = "demo group"
GROUP_DESCRIPTION = "Galène demo server"
GROUP_CONTACT = ""
GROUP_COMMENT = "A small demo server for Galène"
GROUP_MAX_CLIENTS = "20"
GROUP_ALLOW_RECORDING = "false"
GROUP_ALLOW_ANONYMOUS = "false"
GROUP_ALLOW_SUBGROUPS = "false"
GROUP_AUTOLOCK = "false"
GROUP_AUTOKICK = "false"

[port.web]
container = { key="LISTEN_PORT" }
host = { key="LISTEN_PORT" }

[docker]
network = "host"
restart_policy.name = "always"

[[volume]]
name = "galene_groups"
target = "/nua/app/groups"

[[volume]]
name = "galene_data"
target = "/nua/app/data"

[backup]
method = "tgz_volumes"
frequency = "24h"
options = { destination = "local" }
