[metadata]
id = "echo-two-ports"
version = "1.0"
release = 2
title = ""
author = "Nua test server 2 ports"
tagline = "Nua test server 2 ports"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
licence = "MIT"

[port.web]
container = 8765
host = "auto" # default
protocol = "tcp" # default
# proxy = "auto" # default: "auto" for first port, "None" for next ones, or a port value (int).

[ports.abcd]
container = 8764
host = 8764 # default
protocol = "tcp" # default
# proxy = "none" # default: "auto" for first port, "None" for next ones, or a port value (int).
