repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.292'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
      # Not working (?)
      # args: ["--force-exclude"]
      # Using this instead:
      exclude: (apps|demo|nua)

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    # Generic
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    # - id: check-shebang-scripts-are-executable
    - id: check-merge-conflict
    - id: check-symlinks
    # Basic syntax checks
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    # Security
    - id: detect-private-key
    # - id: detect-aws-credentials
    # Whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
    # Misc Python
    - id: debug-statements
    - id: check-docstring-first
    - id: forbid-new-submodules
      args: ['--allow-missing-credentials']
    - id: fix-encoding-pragma
      args: ['--remove']
    # - id: name-tests-test
    # - id: no-commit-to-branch
    # - id: requirements-txt-fixer


-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
