[tool.poetry]
name = "nua-master"
version = "0.1.0"
description = ""
authors = ["Stefane Fermigier <sf@abilian.com>"]
license = "AGPL"


[tool.poetry.dependencies]
python = "^3.10"

nua-lib = { path = "nua-lib", develop = true }
nua-runtime = { path = "nua-runtime", develop = true }
nua-autobuild = { path = "nua-autobuild", develop = true }
nua-build = { path = "nua-build", develop = true }
nua-orchestrator = { path = "nua-orchestrator", develop = true }


[tool.poetry.group.dev.dependencies]
# Testing / checking
nox = "*"
abilian-devtools = "*"

# Typing
types-setuptools = "*"
types-paramiko = "*"
types-requests = "*"

# Formatting
isort = "^5.10.1"
black = "^22.3.0"

# Docs
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.14"
mkdocs-material-extensions = "^1.0.3"
mkdocs-roamlinks-plugin = "^0.1.3"
mkdocs-with-pdf = "^0.9.3"
mkdocstrings = {extras = ["python"], version = "^0.19"}
sqla2uml = "^0.1.2"
pygments = "^2.12.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# ------------------------------------------------------------------------------

[tool.ruff]
select = [
    "F",
    "E",
    "C90",
    # "I", <- too many false positives for some reason(s)
    "UP",
    "N",
    "YTT",
    "B",
    "A",
    "C4",
    "ICN",
    "Q",
    "S",
    "BLE",
    "RET",
    "SIM",
    "TID",
    "RUF",
    "PLC", "PLE", "PLR", "PLW",
]
# Add later: "ANN", "ERA"...

ignore = [
    # FIXME: this is easy to test
    "E501",  # line too long
    "F401",  # 'module' imported but unused
    "I001",  # Import block is un-sorted or un-formatted
    'E711', # comparison to None should be 'if cond is not None:'
]
extend-exclude = [
    # XXX: check later
    "apps",
    "demo",
    "nua",
]
