[tool.poetry]
name = "nua-master"
version = "0.1.0"
description = ""
authors = ["Stefane Fermigier <sf@abilian.com>"]
license = "AGPL"


[tool.poetry.dependencies]
python = "^3.10"

nua-lib = { path = "nua-lib", develop = true }
nua-cli = { path = "nua-cli", develop = true }
nua-runtime = { path = "nua-runtime", develop = true }
nua-autobuild = { path = "nua-autobuild", develop = true }
nua-build = { path = "nua-build", develop = true }
nua-orchestrator = { path = "nua-orchestrator", develop = true }


[tool.poetry.group.dev.dependencies]
# Testing / checking
nox = "*"
abilian-devtools = "*"

# Helper for monorepo
invoke = "^1.7.3"

# Code coverage (reporting)
codecov = "*"

# Typing
types-setuptools = "*"
types-paramiko = "*"
types-requests = "*"

# Docs
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.14"
mkdocs-material-extensions = "^1.0.3"
mkdocs-roamlinks-plugin = "^0.1.3"
mkdocs-with-pdf = "^0.9.3"
mkdocstrings = {extras = ["python"], version = "^0.19"}
sqla2uml = "^0.1.2"
pygments = "^2.12.0"
autotyping = "^22.9.0"
pytest-monkeytype = "^1.1.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# ------------------------------------------------------------------------------

[tool.ruff]
select = [
    "F",
    "E",
    "C90",
    "I",
    "UP",
    "N",
    "YTT",
    "B",
    "A",
    "C4",
    "ICN",
    "Q",
    "S",
    "BLE",
    "RET",
    "SIM",
    "TID",
    "RUF",
    "PLC", "PLE", "PLR", "PLW",
]
# Add later: "ANN", "ERA"...

extend-exclude = [
    ".nox",
    # XXX: check later
    "apps",
    "demo",
    "nua",
]
