[tool.poetry]
name = "nua"
version = "0.1.0"
description = ""
authors = ["Stefane Fermigier <sf@abilian.com>"]
license = "AGPL"


[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.dev-dependencies]

# Docs
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.14"
mkdocs-material-extensions = "^1.0.3"
mkdocs-roamlinks-plugin = "^0.1.3"
sqla2uml = "^0.1.2"
mkdocs-with-pdf = "^0.9.3"
mkdocstrings = {extras = ["python"], version = "^0.18.1"}


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
