[metadata]
id = "flask-at-start"
version = "1.0"
release = 1
title = "Flask crete file at start"
author = "Nua testers"
tagline = "Nua test with Flask - at_start"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "start"]
license = "MIT"

[build]
document-root = "/var/lib"
test = "python -c 'import sample_app'"

[run]
start = "gunicorn --worker-tmp-dir /dev/shm --workers 1 -b :3000 sample_app.wsgi:app"

[env]
MY_IP = { external_ip='true' }
DOMAIN = { key="domain" }
TITLE = "Some title"
WWW_DIR = "/var/lib/sample_www"

[docker]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 3000

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "tmpfs"
target = "/var/lib/sample_www"
tmpfs_size = "2G"
tmpfs_mode = "1777"
