[metadata]
id = "flask-one-wheel-auto"
version = "1.3"
release = 3
title = "Flask test one wheel auto"
author = "Nua testers"
tagline = "Nua test with Flask - one"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
license = "MIT"

[build]
test = "python -c 'import flask_one_wheel'"

[port.web]
container = 8080
