[db]
    backend = "sqlite"
    local_dir = "/var/tmp/nua"
    url = "sqlite:////var/tmp/nua/nua_build.db"
    echo = false
[host]
    host_user = "nua"
    host_home = "/home/nua"
    host_priv_key_blob = ""
[[container]]
    format = "docker"
    transport = "ssh"
    repository = "registry"
[registry.local]
    container.tag = "registry:2.8"
    container.name = "nua-registry"
    address = "127.0.0.1"
    cont_port = "5000"
    host_port = "5010"
    volume.path = "/var/tmp/nua/registry/data"
    volume.env = "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY"
