[db]
    backend = "sqlite"
    local_dir = "/home/nua/db"
    url = "sqlite:////home/nua/db/nua.db"
    echo = false
[host]
    host_user = "nua"
    host_home = "/home/nua"
    host_priv_key_blob = ""
[server]
    log_file = "//home/nua/log/nua_orchestrator.log"
[[container]]
    format = "docker"
    transport = "ssh"
    repository = "registry"
# [registry.local]
#     container.tag = "registry:2.8"
#     container.name = "nua-registry"
#     address = "127.0.0.1"
#     cont_port = "5000"
#     host_port = "5010"
#     volume.path = "/var/tmp/nua/registry/data"
#     volume.env = "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY"
