[metadata]
id = "flask-one-setup"
version = "1.2"
title = "Flask test one setup"
author = "Nua testers"
tagline = "Nua test with Flask - one - setup"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
licence = "MIT"
profile = ["test"]
release = 1

[build]
document_root = "/nua/app/html"

[run]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
