[metadata]
id = "flask-one-setup"
version = "1.2"
title = "Flask test one setup"
author = "Nua testers"
tagline = "Nua test with Flask - one - setup"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
licence = "MIT"
profile = ["test"]
release = 3

[build]
document_root = "/nua/app/html"

# See later if "src_url" is the same concept.
project = "."

test-cmd = "python -c 'import flask_one_setup'"

[run]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
