[metadata]
id = "flask-sqla-sqlite-volume"
version = "1.1"
release = 4
title = "Nua test with sqlalchemy, sqlite on docker managed volume"
author = "Nua testers"
tagline = "Nua test with sqlalchemy, sqlite on docker managed volume"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "flask", "plugin", "sqlite", "sqlalchemy"]
license = "MIT"

[build]
test = "python -c 'import flask_sqla_sqlite_volume'"

[env]
"DB_NAME" = { from="database", key="SQLITE_DB" }
"DB_FOLDER" = { from="database", key="SQLITE_DIR" }

[docker]
auto_remove = false # default

[port.web]
container = 5000

[[resource]]
name = "database"
plugin-name = "sqlite"
