image: ubuntu/lts

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  # Python
  - python3-dev
  - python3-pip
  - python3-wheel
  - tox
  # Libraries
  - libpq-dev
  - libffi-dev
  - libsqlite3-dev
  - libbz2-dev
  # Tools
  - vagrant
  - virtualbox
  - docker.io

tasks:
  - setup: |
      sudo pip install -U pip setuptools wheel poetry nox
      cd nua
      poetry install
      poetry run invoke install

  - lint: |
      cd nua
      poetry run invoke lint

  - e2e: |
      cd nua
      poetry install
      cd tests/e2e
      poetry run make test

  - nox: |
      cd nua
      poetry run nox

  - test: |
      cd nua
      poetry run invoke test


triggers:
  - action: email
    condition: failure
    to: builds@fermigier.com
