[metadata]
id = "etherpad-lite"
version = "1.8.18"
release = 1
title = "etherpad-lite"
author = "etherpad-lite authors"
tagline = "A real-time collaborative editor for the web"
description = "Etherpad: A modern really-real-time collaborative document editor."
website = "https://etherpad.org"
license = "Apache-2.0"
src-url = "https://github.com/ether/etherpad-lite/archive/{version}.tar.gz"
checksum = "67ccc0bac94e146b26fbddcf8330e0f543a4ff82213c420a376644614a7ff2c4"

[build]
builder = "node-14"
run-packages = [
    "git"  # to check
]

build-command = "true"  # aka do nothing

[run]
start = "./src/bin/run.sh"

[env]
NODE_ENV = "production"
TIMEZONE = "Europe/Paris"

[port.web]
container = 9001
