[metadata]
id = "ackee"
title = "Ackee"
author = "Ackee authors"
description = "Self-hosted, Node.js based analytics tool for those who care about privacy."
website = "https://ackee.electerious.com"
version = "3.4.2"
release = 1
license = "MIT"

src-url = "https://github.com/electerious/Ackee/archive/v{version}.tar.gz"

[build]
build-packages = []
