[metadata]
id = "flask-mariadb-wheel"
version = "1.0"
release = 4
title = "Flask/MariaDB test wheel"
author = "Nua testers"
tagline = "Nua test with Flask/MariaDB"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "MariaDB"]
license = "MIT"

[build]
meta-packages = ["mariadb-client"]
pip-install = ["*.whl"]
test = "python -c 'import flask_mariadb_wheel'"



[[assign]]
key = "MARIADB_PASSWORD"
random_str = true

[[assign]]
key = "DB_USER_PWD"
random_str = true

[env]
# parameters passed as a dict to docker run: environment dict
DB_NAME = "flask_db"
DB_USER = "bob"

[docker]
# parameters passed as a dict to docker run
# auto_remove = true
# detach = true mandatory

[port.web]
container = 80

[[provider]]
# A provider is another container required by the main app container, its
# configuration is described below, under the key of name of the provider. Several
# providers can be declared. The provider host will appear in the local network
# with a hostname equal to the container name. The name of the provider hostname
# is available in the environment variable NUA_${name_of_the_provider}_HOST, ie in
# this example: NUA_DATABASE_HOST

# declaration of the required image for the provider, here the local mariadb
# Docker image
name = "database"
# type = "local"
# service = "mariadb"
