[[site]]
image = "nua-flask-pg-via-orch"
domain = "test1.example.com"

[[site]]
image = "nua-flask-pg-via-orch"
domain = "test2.example.com"

[[site]]
image = "nua-flask-pg-via-orch"
domain = "test3.example.com"
