[[site]]
image = "flask-pg-psyco:5.0-1"
domain = "test1.example.com"
[site.run.env]
DB_NAME = "flask_db_1"

[[site]]
image = "flask-pg-psyco:5.0-1"
domain = "test2.example.com"
[site.run.env]
DB_NAME = "flask_db_2"
DB_USER = "bob2"
DB_USER_PWD = "bob_pwd_2"
