[metadata]
id = "flask-one-setup"
version = "1.2"
title = "Flask test one setup"
author = "Nua testers"
tagline = "Nua test with Flask - one - setup"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
license = "MIT"
profile = ["test"]
release = 3

[build]
document_root = "/nua/app/html"
project = "."
test = "python -c 'import flask_one_setup'"

[run]
start = "gunicorn --worker-tmp-dir /dev/shm --workers 2 -b :80 flask_one_setup.wsgi:app"

[docker]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
