ARG nua_min_tag
FROM ${nua_min_tag} AS compile-image

ARG nua_version
COPY nua_build_${nua_version} /nua/nua_build
RUN apt-get install -y build-essential git
RUN python -m pip install poetry && cd /nua/nua_build && poetry install && nuad setup_nua

FROM ${nua_min_tag} AS runtime-image
COPY --from=compile-image /nua /nua
