[metadata]
id = "new-redis-cache-test-no-plugin"
version = "1.0"
release = 1
title = "Redis cache test"
author = "Nua testers"
tagline = "Redis cache test"
website = "https://nua.rocks/"
tags = ["test", "redis"]
license = "MIT"

[build]
test = "python -c 'import redis_cache_test'"

[run]
start = "python -c 'from redis_cache_test.app import main; main()'"

[env]
REDIS_HOST = { from="database", key="hostname" }
REDIS_PORT = { from="database", key="REDIS_PORT" }

[port.web]
container = 5000

[[resource]]
# declaration of the required image for the resource: official Redis image
name = "database"
type = "docker-image"
base-image = "docker.io/amd64/redis:7.0.8"
[resource.env]
REDIS_PORT = "6379"
[resource.docker]
detach = true
