[metadata]
id = "flask-upload-sshfs"
version = "1.0"
release = 4
title = "Flask test upload on sshfs volume"
author = "Nua testers"
tagline = "Nua test with Flask and mount - sshfs"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "mount", "plugin", "sshfs"]
license = "MIT"

[build]
test = "python -c 'import flask_upload_sshfs'"

[docker]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80

[[volume]]
type = "managed"
driver = "sshfs"
name = "flask_uploads"
target = "/var/tmp/uploads"
# password = "testpassword"  # if passaword auth
options = { sshcmd = "user@remote.com:/var/test", IdentityFile = "/nua/some_private_key" }
