[[site]]
image = "nua-flask-upload-tmpfs"
domain = "test1.example.com"

[[site]]
image = "nua-flask-upload-tmpfs"
domain = "test2.example.com"

[[site]]
image = "nua-flask-upload-tmpfs"
domain = "test3.example.com"
