[[site]]
label = "upload"
image = "nua-flask-upload-tmpfs"
domain = "test1.example.com"

[[site]]
label = "upload2"
image = "nua-flask-upload-tmpfs"
domain = "test2.example.com"

[[site]]
label = "upload3"
image = "nua-flask-upload-tmpfs"
domain = "test3.example.com"
