[metadata]
id = "flask-sqla-postgresql"
version = "1.0"
release = 8
title = "Flask + SQLA + Postgres demo app"
description = "A demo app using Flask, SQLAlchemy and PostgreSQL"
author = "Nua developers"
website = "https://nua.rocks/"
tags = ["Demo", "Python", "Flask", "PostgreSQL", "SQLAlchemy", "psycopg2"]

[build]
license = "MIT"
test = "python -c 'import flask_app'"

[run]
start = [
	# TODO: --app 'flask_app.app:create_app()' is not really elegant.
	# We should put the wsgi.py file somewhere and use it instead.
	"flask --app 'flask_app.app:create_app()' dump-config",
	"flask --app 'flask_app.app:create_app()' init-db",
	"gunicorn --workers 2 -b :5000 'flask_app.app:create_app()'",
]

[env]
DB_HOST = { from="database", key="hostname" }
DB_PORT = { from="database", key="POSTGRES_PORT" }
DB_NAME = { from="database", key="POSTGRES_DB" }
DB_USERNAME = { from="database", key="POSTGRES_USER" }
DB_PASSWORD = { from="database", key="POSTGRES_PASSWORD" }

[docker]
restart_policy.name = "always"

[port.web]
# publication port of the app inside the container
container = 5000

[[provider]]
# declaration of the required image for the provider, here the official Postgres
# Docker image
name = "database"
module-name = "postgres"
module-version = ">=14, <15"
