[metadata]
id = "hedgedoc"
version = "1.9.7"
# Nota: version 1.9.6 seems broken since 1.9.7
release = 3
title = "Hedgedoc"
author = "Hedgedoc authors"
tagline = "The best platform to write and share markdown"
website = "https://hedgedoc.org/"
tags = ["Markdown", "Documentation", "Collaboration"]
license = "AGPL-3.0 license"
src-url = "https://github.com/hedgedoc/hedgedoc/releases/download/{version}/hedgedoc-{version}.tar.gz"
checksum = 'c9bd99c65cf45fa1d7808855b46abbfa13b24400254d8da5e81dae2965494bb3'

[build]
# use a specific docker image containing nodejs:
builder = "node-14"

run-packages = [
    "fontconfig",
    "fonts-noto"
]

build-packages = [
    "build-essential",
    "python3-dev",
    "libsqlite3-dev",
    "netcat",
    "libicu-dev",
    "libssl-dev",
    "git",
]

build-command = [
    "bin/setup",
    "yarn cache clean; rm -fr /tmp/*"
]
test = "test -f /nua/build/hedgedoc/healthcheck.mjs"

[run]
start = "node app.js"

[env]
# Generic environment variables
NODE_ENV = "production"
DEBUG = "true"
UPLOADS_MODE = "0700"
TZ = "Europe/Paris"

# Env variables prefixed with CMD_ are specific to Hedgedoc
# (which used to be called CodiMD, hence "CMD_")

# IMPORTANT: to be set at the actual domain deployed
CMD_DOMAIN = { from="", key="domain" }
CMD_ALLOW_ORIGIN = { key="domain" }

CMD_DB_HOST = { from="database", key="hostname" }
CMD_DB_DATABASE = { from="database", key="POSTGRES_DB" }
CMD_DB_USERNAME = { from="database", key="POSTGRES_USER" }
CMD_DB_PASSWORD = { from="database", key="POSTGRES_PASSWORD" }

CMD_HSTS_ENABLE = "false"
# URL_ADDPORT defines if generated links should contain the port.
CMD_URL_ADDPORT = "false"
# if not using HTTPS, set the CMD_PROTOCOL_USESSL to false:
# CMD_PROTOCOL_USESSL = "false"
CMD_PROTOCOL_USESSL = "true"

# See https://docs.hedgedoc.org/configuration/#users-and-privileges
CMD_ALLOW_ANONYMOUS = "true"
CMD_ALLOW_ANONYMOUS_EDITS = "true"

CMD_EMAIL = "true"
CMD_ALLOW_EMAIL_REGISTER = "true"

# postgres:
CMD_DB_PORT = "5432"
CMD_DB_DIALECT = "postgres"

[docker]
# parameters passed as a dict to docker run
auto_remove = false

[port.web]
container = 3000

[healthcheck]
command = "node /nua/build/hedgedoc/healthcheck.mjs"
interval = 10

[[volume]]
# declare a local volume for plublic uploads
# bind example: type = "bind"
type = "volume"

# Name of the driver used to create the volume: (for type == "volume")
# driver = "local"  # default for "volume" type
# Mount source (e.g. a volume name or a host path):
prefix = "hedgedoc_uploads"
# Container path:
target = "/hedgedoc/public/uploads"

[volume.backup]
method = "sync"
destination = "local"
frequency = "24h"

[[resource]]
# A resource is another container required by the main app container, its
# configuration is described below, under the key of name of the resource. Several
# resources can be declared. The resource host will appear in the local network
# with a hostname equal to the container name.

# Declaration of the required image for the resurce, here the official Postgres.
name = "database"
type = "postgres"
version = ">=14, <15"

[resource.backup]
method = "pg_dumpall"
destination = "local"
frequency = "24h"
