metadata:
  author: Jerome Dumonteil <jd@abilian.com>
  id: echo-two-ports-yaml
  license: MIT
  release: 2
  tagline: Nua test server 2 ports
  tags:
  - test
  - html
  - web
  - static
  title: Nua test server 2 ports - yaml config
  version: '1.0'
  website: https://nua.rocks/
build:
  pip-install:
  - "*.whl"
  test: "python -c 'import echo_two_ports'"
port:
  web:
    container: 8765
    proxy: 8765
ports:
  abcd:
    container: 8764
    host: 8764
    proxy: 8764
