metadata:
  author: Jerome Dumonteil <jd@abilian.com>
  id: echo-two-ports-yaml
  license: MIT
  release: 3
  tagline: Nua test server 2 ports
  tags:
  - test
  - html
  - web
  - static
  title: Nua test server 2 ports - yaml config
  version: '1.0'
  website: https://nua.rocks/
build:
  pip-install:
  - "*.whl"
  test: "python -c 'import echos'"
run:
  start: "python -c 'from echos.echo_server import echos; echos(8764, 8765)'"
port:
  web:
    container: 8765
ports:
  abcd:
    container: 8764
    proxy: 8764
