[metadata]
id = "flask-upload-tmpfs"
version = "1.0"
release = 5
title = "Flask test upload with container tmpfs"
author = "Nua testers"
tagline = "Flask test upload with with container tmpfs"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "tmpfs"]
license = "MIT"

[build]
test = "python -c 'import flask_upload_tmpfs'"

[port.web]
container = 80

[[volume]]

type = "tmpfs"
target = "/var/tmp/mount_point"
    [[volume.options]]
    tmpfs_size = "10G"
    tmpfs_mode = 0o1777
