[metadata]
id = "flask-upload-tmpfs"
version = "1.0"
release = 4
title = "Flask test upload with container tmpfs"
author = "Nua testers"
tagline = "Flask test upload with with container tmpfs"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "tmpfs"]
license = "MIT"

[build]
document-root = "/nua/app/html"
test = "python -c 'import flask_upload_tmpfs'"

[run]
start = "gunicorn --worker-tmp-dir /dev/shm --workers 2 -b :8000 flask_upload_tmpfs.wsgi:app"

[port.web]
container = 8000

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "tmpfs"
# Name of the driver used to create the volume: (for type == "volume")
target = "/var/tmp/mount_point"
tmpfs_size = "10G"
tmpfs_mode = 0o1777
