[db]
    backend = "sqlite"
    local_dir = "/var/tmp/nua"
    url = "sqlite:////var/tmp/nua/nua_build.db"
    echo = false
[host]
    host_user = "nua"
    host_home = "/home/nua"
    host_priv_key_blob = ""
[server]
    pid_file = "/tmp/nua/orchestrator.pid"
    exit_flag = "/tmp/nua/orchestrator_exiting.pid"
    log_file = "/tmp/nua_orchestrator.log"
    start_zmq_server = true
    start_sshd_server = true
[[container]]
    format = "docker"
    transport = "ssh"
    repository = "registry"
[connection]
    connect_timeout = 10
[connection.connect_kwargs]
    key_filename = "~/.ssh/id_rsa"
[registry.local]
    container.tag = "registry:2.8"
    container.name = "nua-registry"
    address = "127.0.0.1"
    cont_port = "5000"
    host_port = "5010"
    volume.path = "/var/tmp/nua/registry/data"
    volume.env = "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY"
[zmq]
    address = "127.0.0.1"
    port = 5002
[ssh]
    address = "127.0.0.1"
    port = 5022
    # host_key = "/home/nua/ssh_host_keys/nua_host_rsa"
    # auth_keys_dir = "/home/nua/ssh_authorized_keys"
    # host_key = "/tmp/nua/ssh_host_keys/nua_host_rsa"
    auth_keys_dir = "/tmp/nua/ssh_authorized_keys"
    admin_auth_keys_dir = "/tmp/nua/ssh_admin_authorized_keys"
    work_dir = "/tmp"
    log_file = "/tmp/nua_ssh.log"
[rpc]
    status_show_all = true
[[rpc.plugin]]
    module = "nua_plugin_test.methods.test_plugin"
    class = "RPCPluginTest"
