[metadata]
id = "flask-upload-bind-mount"
version = "1.0"
release = 3
title = "Flask test upload with host local dir (Docker option -v)"
author = "Nua testers"
tagline = "Flask test upload with host local dir (Docker option -v)"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "bind", "--volume"]
license = "MIT"

[build]
document-root = "/nua/app/html"
# - should auto detect local python project
# - should create automatically the source volume if needed

test-cmd = "python -c 'import flask_upload_bind_mount'"

[env]
# parameters passed as a dict to docker run: environment dict
UPLOAD_DIRNAME = "uploads_local"

[port.web]
container = 80

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "bind"
# Name of the driver used to create the volume: (for type == "volume")
# driver = "local"
# Mount source (e.g. a volume name or a host path):
# the directory must exits or will be created
source = "/var/tmp/nua_test"
# Container path:
target = "/var/tmp/mount_point"
#[[mount.opt]]
# list of volume-op tags
# docker.types.Mount
# volume = client.volumes.create(name='foobar', driver='local',
#   driver_opts={'foo': 'bar', 'baz': 'false'},
#   labels={"key": "value"})
