[metadata]
id = "flask-mariadb-wheel"
version = "1.0"
release = 2
title = "Flask/MariaDB test wheel"
author = "Nua testers"
tagline = "Nua test with Flask/MariaDB"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "MariaDB"]
licence = "MIT"

[build]
document_root = "/nua/app/html"

[[assign]]
key = "MARIADB_PASSWORD"
random_str = true

[[assign]]
key = "DB_USER_PWD"
random_str = true

[run]
# parameters passed as a dict to docker run
# auto_remove = true
# detach = true mandatory

[run.env]
# parameters passed as a dict to docker run: environment dict
DB_NAME = "flask_db"
DB_USER = "bob"

[port.web]
container = 80

[[resource]]
# A resource is another container required by the main app container, its
# configuration is described below, under the key of name of the resource. Several
# resources can be declared. The resource host will appear in the local network
# with a hostname equal to the container name. The name of the resource hostname
# is available in the environment variable NUA_${name_of_the_resource}_HOST, ie in
# this example: NUA_DATABASE_HOST

# declaration of the required image for the resource, here the local mariadb
# Docker image
name = "database"
type = "local"
service = "mariadb"
