[metadata]
id = "adhocracy-plus"
title = "adhocracy-plus"
author = "adhocracy-plus authors"
description = "adhocracy+ is a SaaS platform to make digital democracy easy for everyone"
website = "https://adhocracy.plus/"
version = "2301"
release = 1
license = "AGPL-3.0"

src-url = "https://github.com/liqd/adhocracy-plus/archive/v{version}.tar.gz"

[build]
build-packages = [
    "git",
    # Needed to build psycopg2
    "gcc",
    "python3-dev",
    "libpq-dev",
]
