[metadata]
id = "demo-flask"
version = "0.1"
title = "Flask Demo"
author = "Abilian"
tagline = "Simple demo"
src-url = "https://github.com/abilian/flask-nua-demo/archive/refs/tags/{version}.tar.gz"
src-checksum = ""

[build]
license = "MIT"
# app pyproject broken ? need to force install of dependencies
pip-install = ["flask", "gunicorn"]

test = "python -c 'import app'"

[port.web]
container = 80
host = 5000
