[metadata]
id = "demo-flask"
version = "0.1"
title = "Flask Demo"
author = "Abilian"
tagline = "Simple demo"
license = "MIT"
src-url = "https://github.com/abilian/flask-nua-demo/archive/refs/tags/{version}.tar.gz"
src-checksum = ""

[build]
# app pyproject broken ? need to force install of dependencies
pip-install = ["flask", "gunicorn"]
# project explicit declaration reuired since we have some prior pip install
project = "https://github.com/abilian/flask-nua-demo/archive/refs/tags/{version}.tar.gz"

test-cmd = "python -c 'import app'"

[port.web]
container = 80
host = 5000
