# Project info
site_name: Nua doc
site_description: The official website and documentation site for the Nua self-sovereign cloud platform project
site_author: Abilian SAS
site_url: https://nua.rocks/

docs_dir: src

# Copyright
copyright: Copyright &copy; 2021-2022 Abilian SAS

# Repository
repo_name: 'abilian/nua'
repo_url: 'https://github.com/abilian/nua'
edit_uri: 'https://github.com/abilian/nua/blob/master/docs/'

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book-open-page-variant
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: dark-blue
      # accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant

extra:
  homepage: https://nua.rocks
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abilian/nua
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/abilianhq
  analytics:
    provider: custom


# Extensions
markdown_extensions:
  - meta
  - footnotes
  - toc:
      permalink: true
  - smarty
  - sane_lists
  - nl2br
  - fenced_code
  - pymdownx.magiclink
  - pymdownx.tasklist
  # - pymdownx.superfences

plugins:
  - search
  - roamlinks
  - with-pdf:
      author: Stefane Fermigier / Jérôme Dumonteil
      copyright: © 2022 Abilian
      cover: true
      back_cover: false
      cover_title: Nua
      cover_subtitle: Self-sovereign cloud platform
      enabled_if_env: ENABLE_PDF_EXPORT

      #    custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         rendering:
  #           show_source: false
  #     custom_templates: templates
  #     watch:
  #       - ../src/app

nav:
  - Home: index.md
  - Developers:
    - Intro: dev/index.md
    - Architecture: dev/architecture.md
    - Database: dev/database.md
    - Open Source Librairies (back-end): dev/libraries.md
    - API (back-end): dev/api.md
    - Front-End: dev/front-end.md
  - Users:
    - Intro: user/index.md
    
