[plugin]
name = "sqlite"
format = "package"
family = "db"
network = true
meta-packages = []
options = []

[env]
SQLITE_DIR = "/nua/app/sqlite"
SQLITE_SOURCE = "sqlite-data"

[env.SQLITE_DB]
unique_db = true
persist = true

[docker]
detach = true

[docker.restart_policy]
name = "always"

[volume]
name = "sqlite-data"
type = "managed"
driver = "docker"
target = "/nua/app/sqlite"
