[metadata]
id = "flask-upload-bind-mount"
version = "1.0"
release = 5
title = "Flask test upload with host local dir (Docker option -v)"
author = "Nua testers"
tagline = "Flask test upload with host local dir (Docker option -v)"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "bind", "--volume"]

[build]
license = "MIT"
test = "python -c 'import flask_upload_bind_mount'"

[env]
# parameters passed as a dict to docker run: environment dict
UPLOAD_DIRNAME = "uploads_local"

[port.web]
container = 80

[[volume]]
type = "directory"
name = "/var/tmp/nua_test"
target = "/var/tmp/mount_point"
