# Default Nua config file for moinmoin:

[metadata]
id = "moinmoin"
version = "2.0-pre"
title = "Moinmoin"
author = "Moinmoin authors"
tagline = "An advanced, easy to use and extensible Wiki engine with a large community of users"
website = "https://moinmo.in/"
tags = ["wiki", "collaboration", "notes", "documents"]
licence = "GNU General Public License"
profile = ["generic"]



[build]
# optional manifest.
# if no manifest, use files in the repository (except dot files)
# - Manifest do not ccept directory (currently)
# - if manifest is not empty, *only* files from manifest are copied
# - "nua-config.toml" is always copied, wether local or not
manifest = [
# use Nua default Dockerfile:
# Dockerfile,
# use Nua default nua-setup.py (recommanded):
# 'nua-setup.py',
'start.py',
]
#src_url = "https://github.com/moinwiki/moin/archive/refs/heads/master.tar.gz"
src_git = "https://github.com/moinwiki/moin.git"
