[metadata]
id = "moinmoin"
version = "2.0-pre"
title = "Moinmoin"
author = "Moinmoin authors"
tagline = "An advanced, easy to use and extensible Wiki engine with a large community of users"
website = "https://moinmo.in/"
tags = ["wiki", "collaboration", "notes", "documents"]
licence = "GNU General Public License"
profile = ["generic"]


[build]
#src_url = "https://github.com/moinwiki/moin/archive/refs/heads/master.tar.gz"
src_git = "https://github.com/moinwiki/moin.git"
