[metadata]
id = "flask-one-wheel"
version = "1.2"
release = 3
title = "Flask test one wheel"
author = "Nua testers"
tagline = "Nua test with Flask - one"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
license = "MIT"

[build]
pip-install = ["*.whl"]
document-root = "/nua/app/html"
test-cmd = "python -c 'import flask_one_wheel'"

[port.web]
container = 80
