[metadata]
id = "demo-flask"
version = "0.1"
title = "Flask Demo"
author = "Abilian"
tagline = "Simple demo"
runtimes = ["python"]

[build]
src_url = "https://github.com/abilian/flask-nua-demo/archive/refs/tags/{version}.tar.gz"
src_checksum = ""

[env]
PORT = 5000
