[[site]]
image = "flask-pg-dock-psyco:1.0-1"
domain = "test1.example.com"
[site.env]

[[site.test]]
url = "https://test1.example.com/"
expect_status = 200
expect_str = "Books"
[[site.test]]
url = "https://test1.example.com/create/"
expect_status = 200
expect_str = "Add a New Book"


[[site]]
image = "flask-pg-dock-psyco:1.0-1"
domain = "test2.example.com"

# the only changes required are to use a different network and
# redefine the site volumes (to use a different data location).
network = "flask-pg-2"
[[site.resource]]
    name = "database"
[[site.resource.volume]]
    # here we declare a mounted volume (ie: managed by Docker daemon)
    # The mount type (bind / volume / tmpfs / npipe). Default: volume :
    type = "volume"
    # Name of the driver used to create the volume: (for type == "volume")
    driver = "local"
    # Mount source (e.g. a volume name or a host path):
    source = "postgres_data_pg_2"
    # Container path:
    target = "/var/lib/postgresql/data"
    # mode (default to 'rw'
    mode = "rw"

[[site.test]]
url = "https://test2.example.com/"
expect_status = 200
expect_str = "Books"
[[site.test]]
url = "https://test2.example.com/create/"
expect_status = 200
expect_str = "Add a New Book"
