[metadata]
id = "frappe-erpnext"
version = "13.0"
title = "Frappe/ERPNext test"
author = "Nua testers"
tagline = "Nua test with ERPNext"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "MariaDB"]
license = "MIT"
profile = ["test"]
release = 1

[build]
# optional manifest.
# if no manifest, use files in the repository (except dot files)
# - if manifest is not empty, *only* files from manifest are copied
# - "nua-config.toml" is always copied, wether local or not
# manifest = [
# # if no Dockerfile provided => use Nua default Dockerfile:
# "Dockerfile",
# "www",
# "build.py"
# ]

# src_url = "https://github.com/moinwiki/moin/archive/refs/heads/master.tar.gz"
# src_git = "https://github.com/moinwiki/moin.git"

# optional build script, default is "build.py" if found
# build_script = ""
# optional start script, default is "start.py" if found
# start_script = ""
document_root = "/nua/app/html"

[instance]
# instance contains values suited to be chaned at deploy time for
# multi-instance deployment. Values here are used by default, i.e. for a single
# deployment of the app
# port = 5200
# this configuration is for use of a local DB (localhost)
# thus requiring --add-host=host.docker.internal:host-gateway
# services = "mariadb"

[instance.user_passwd]
key = "DB_USER_PWD"
persistent = true
random_str = true

[run]
# parameters passed as a dict to docker run
# auto_remove = true
# detach = true mandatory
[run.env]
# parameters passed as a dict to docker run: environment dict
DB_NAME = "flask_db"
DB_USER = "bob"
# DB_USER_PWD = "bob_pwd"

[port.web]
container = 80
[[resource]]
# A resource is another container required by the main app container, its
# configuration is described below, under the key of name of the resource. Several
# resources can be declared. The resource host will appear in the local network
# with a hostname equal to the container name. The name of the resource hostname
# is available in the environment variable NUA_${name_of_the_resource}_HOST, ie in
# this example: NUA_DATABASE_HOST

# declaration of the required image for the resurce, here the official Postgres
# Docker image
# name = "database"
# type = "local"
# service = "mariadb"
