[metadata]
id = "redis-cache-test"
version = "1.0"
release = 2
title = "Redis cache test"
author = "Nua testers"
tagline = "Redis cache test"
website = "https://nua.rocks/"
tags = ["test", "redis"]
license = "MIT"

[build]
start-command = "python -c 'from redis_cache_test.app import main; main()'"
test = "python -c 'import redis_cache_test'"

[env]
REDIS_HOST = { from="database", key="hostname" }
REDIS_PORT = { from="database", key="REDIS_PORT" }

[port.web]
container = 5000

[[resource]]
# declaration of the required image for the resource: official Redis image
name = "database"
type = "redis-cache"
version = ">=7"
