[metadata]
id = "galene"
version = "0.6.2"
release = 3
title = "Galène videoconference server"
author = "Galene authors"
tagline = "Galène videoconference server"
website = "https://galene.org/"
tags = ["golang", "visio"]
licence = "MIT"
git-url = "https://github.com/jech/galene.git"
git-branch = "galene-0.6-branch"

[build]
packages = ['golang-go', 'git']  # go modules need git for VCS version
build-command = [
    "CGO_ENABLED=0 go build -ldflags='-s -w'",
    "cp galene /nua/app",
    "cp LICENCE /nua/app",
    "cp -a static /nua/app",
    "mkdir /nua/app/groups",
    "mkdir /nua/app/data"
]

[run]
start = "/nua/app/galene -insecure -data /nua/app/data -groups /nua/app/groups -static /nua/app/static"

[env]
# GALENE_TURN = ""
# GALENE_TURN=1.2.3.4:1194

[port.web]
container = 8443

# [port.turn]
# container = 1194
# proxy = 1194
# ssl = false

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "bind"
source = "/home/nua/galene/groups"
target = "/nua/app/groups"

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "bind"
source = "/home/nua/galene/data"
target = "/nua/app/data"
