[metadata]
id = "flask-mariadb-docker-wheel"
version = "1.0"
release = 4
title = "Flask/MariaDB-docker test wheel"
author = "Nua testers"
tagline = "Nua test with Flask/MariaDB-docker"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "MariaDB-docker"]
license = "MIT"

[build]
pip-install = ["*.whl"]
document-root = "/nua/app/html"
test = "python -c 'import flask_mariadb_docker_wheel'"

[env]
DB_HOST = { from="database", key="hostname" }
USER_DB = { from="database", key="MARIADB_DATABASE" }
USER_NAME = { from="database", key="MARIADB_USER" }
USER_PASSWORD = { from="database", key="MARIADB_PASSWORD" }

[docker]
restart_policy.name = "always"

[port.web]
# publication port of the app inside the container
container = 80

[[resource]]
# A resource is another container required by the main app container, its
# configuration is described below, under the key of name of the resource. Several
# resources can be declared. The resource host will appear in the local network
# with a hostname equal to the container name. The name of the resource hostname
# is available in the environment variable NUA_${name_of_the_resource}_HOST, ie in
# this example: NUA_MARIADB_HOST
name = "database"
# declaration of the required image for the resurce, here the official Mariadb
# Docker image
type = "mariadb"
version = ">=10.6, <10.7"
