[metadata]
id = "coturn"
version = "4.5.2"
release = 1
title = "Coturn server"
author = "Coturn authors"
tagline = "VoIP media traffic NAT traversal server and gateway"
website = "https://galene.org/"
tags = ["udp", "turn", "voip"]
licence = "TURN Server license"

[build]
packages = ["coturn"]
build-command = "rm -f /etc/turnserver.conf"

[run]
start = "coturn --no-tls --no-dtls -l stdout"

[env]
LISTEN_PORT = 1194
GALENE_USER = "galene"
GALENE_PW = "galene_pw"
DOMAIN = { key="domain" }
REALM = { key="domain_realm" }
EXTERNAL_IP = { external_ip=true }

[docker]
network = "host"
restart_policy.name = "always"

# [port.web]
# EXPOSE 3478 3478/udp 5349 5349/udp

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "tmpfs"
# Name of the driver used to create the volume: (for type == "volume")
# driver = "local"
# Mount source (e.g. a volume name or a host path):
# the directory must exits
# Container path:
target = "/var/lib/coturn"
# tmpfs_size = "4G"
tmpfs_mode = 1777

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "volume"
prefix = "etc_coturn"
target = "/etc/coturn/"
