[metadata]
id = "flask-one-poetry"
version = "1.2"
release = 3
title = "Flask test one poetry auto-detect"
author = "Nua testers"
tagline = "Nua test with Flask - one - poetry auto-detect"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
licence = "MIT"

[build]
document-root = "/nua/app/html"

# See later if "src_url" is the same concept.
project = "."

test-cmd = "python -c 'import flask_one_poetry'"

[docker]
# parameters passed as a dict to docker.run()
auto_remove = true

[port.web]
container = 80
