[metadata]
id = "abilian-sbe"
title = "Abilian Social Business Engine (SBE)"
author = "Abilian"
description = "Abilian SBE is a Python web application framework for building social business applications."
tagline = "Abilian Social Business Engine (SBE)"
tags = ["social", "business", "document", "wiki"]
website = "https://github.com/abilian/abilian-sbe-monorepo"
version = "1.0.4"
release = 32


[build]
license = "GPL"
git-url = "https://github.com/abilian/abilian-sbe-monorepo.git"
git-branch = "main"
packages = [
    # Needed to build psycopg2
    # (todo: replace by psycopg2-binary in pyproject.toml)
    #"build-essential",
    #"libpq-dev",
    #"python3-dev",
    #"libxslt1-dev",
    #"libjpeg-dev",
    #"libffi-dev",
    #"libsqlite3-dev",
    #"libbz2-dev",
    # Server stuff

]
# pip-install = ["psycopg2-binary"]
build = [
    "/usr/bin/npm install lessc",
    "pip install -U poetry",
    "sed -i.bak 's/psycopg2.*=.*$/psycopg2-binary = \"*\"/g' pyproject.toml",
    "poetry lock --no-update",
    "poetry install"
]
test = "python -c 'import abilian.sbe'"


[run]
packages = [
    "nodejs",
    "npm",
    "imagemagick",
    "libmagic1",
    "fontconfig",
    "celery",
    # Other deps (external tools)
    "poppler-utils",
    "imagemagick",
    "libreoffice",
    "default-jdk-headless",
    "postgresql-client"
]

start = [
    "env",
    "sudo mkdir -p /nua/build/abilian-sbe-monorepo/src/instance",
    "sudo chown nua:nua /nua/build/abilian-sbe-monorepo/src/instance",
    "date",
    "celery -A extranet.celery_app worker -l INFO  --logfile=/nua/build/abilian-sbe-monorepo/src/instance.celery.log --detach",
    "date",
    "bash -c 'while :;  do pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -d ${POSTGRES_DB} -t 10 && break; sleep 5; done'",
    "date",
    "flask initdb",
    "flask createuser --role admin --name admin ${ADMIN_MAIL} ${ADMIN_PASSWORD}",
    "gunicorn 'abilian.sbe.app:create_app()' -b :8000 --workers 2 --log-level debug"
]


[env]
DOMAIN = { from="", key="domain" }
LANG = "C.UTF-8"
NODE_ENV = "production"

ADMIN_MAIL = "jd@abilian.com"
ADMIN_PASSWORD = { random="true", type="str", length=12, display="true", persist="true" }

FLASK_SERVER_NAME = "{DOMAIN}"
FLASK_SITE_NAME = "SBE server at {DOMAIN}"
FLASK_SECRET_KEY = { random="true", type="str", length=24, display="true", persist="true" }
FLASK_SQLALCHEMY_DATABASE_URI = "postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
FLASK_MAIL_DEBUG = 0
FLASK_MAIL_SERVER = "{DOMAIN}:25"
FLASK_MAIL_SENDER = "sbe-server@{DOMAIN}"
FLASK_DEBUG = 0

FLASK_REDIS_URI = "{REDIS_URI}"
FLASK_BROKER_URL = "{REDIS_URI}"
FLASK_CELERY_BROKER_URL = "{REDIS_URI}"
CELERY_BROKER_URL = "{REDIS_URI}"
FLASK_CELERY_RESULT_BACKEND = "{REDIS_URI}"
CELERY_RESULT_BACKEND = "{REDIS_URI}"

CLAMD_CONF_PATH = ""

POSTGRES_HOST = { from="database", key="hostname" }
POSTGRES_PORT = "5432"
POSTGRES_DB = { from="database", key="POSTGRES_DB" }
POSTGRES_USER = { from="database", key="POSTGRES_USER" }
POSTGRES_PASSWORD = { from="database", key="POSTGRES_PASSWORD" }

REDIS_HOST = { from="broker", key="hostname" }
REDIS_PORT = { from="broker", key="REDIS_PORT" }
REDIS_URI = "redis://{REDIS_HOST}:{REDIS_PORT}/"


[docker]
# parameters passed as a dict to docker run
auto_remove = false


[port.web]
container = 8000

[[volume]]
name = "instance_path"
target = "/nua/build/abilian-sbe-monorepo/src/instance"


[[provider]]
# A provider is another container required by the main app container, its
# configuration is described below, under the key of name of the provider. Several
# providers can be declared. The provider host will appear in the local network
# with a hostname equal to the container name.

# Declaration of the required image for the resurce, here the official Postgres.
name = "database"
module-name = "postgres"
module-version = ">=14, <15"

[provider.backup]
method = "pg_dump"
options = { destination = "local" }


[[provider]]
# declaration of the required image for the provider: official Redis image
name = "broker"
module-name = "redis-cache"
module-version = ">=7"
