[metadata]
id = "flask-pg-test"
version = "1.0"
release = 1
title = "test feature"
author = "Nua testers"
tagline = "test feature"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "plugin", "PostgreSQL", "docker", "psycopg2"]
licence = "MIT"

[build]
document_root = "/nua/app/html"
project = "."
test-cmd = "python -c 'import flask_pg_test'"


[[assign]]
key = "DB_HOST"
resource_property = "database.hostname"

[[assign]]
key = "DB_PORT"
resource_property = "database.POSTGRES_PORT"

[[assign]]
key = "USER_DB"
resource_property = "database.POSTGRES_DB"

[[assign]]
key = "USER_NAME"
resource_property = "database.POSTGRES_USER"

[[assign]]
key = "USER_PASSWORD"
resource_property = "database.POSTGRES_PASSWORD"

[docker]
restart_policy.name = "always"

[port.web]
# publication port of the app inside the container
container = 5000

[[resource]]
# declaration of the required image for the resource, here the official Postgres
# Docker image
name = "database"
type = "postgres"
version = ">=14, <15"
