[metadata]
id = "apache-basic"
version = "2.4"
title = "Apache basic"
author = "Apache foundation"
tagline = "Apache basic config with static content"
website = "https://apache.org/"
tags = ["html", "web", "static"]
licence = "Apache license"
profile = ["generic"]
release = 1
changelog ="""
* Jun 06 2022 Jerome Dumonteil <jd@abilian.com>
- trying some test with apache
"""

[build]
# optional manifest.
# if no manifest, use files in the repository (except dot files)
# - if manifest is not empty, *only* files from manifest are copied
# - "nua-config.toml" is always copied, wether local or not
# manifest = [
# # if no Dockerfile provided => use Nua default Dockerfile:
# "Dockerfile",
# "www",
# "build.py"
# ]
#src_url = "https://github.com/moinwiki/moin/archive/refs/heads/master.tar.gz"
# src_git = "https://github.com/moinwiki/moin.git"
# optional build script, default is "build.py" if found
# build_script = ""
# optional start script, default is "start.py" if found
# start_script = ""
