[tool.poetry]
name = "nua_build"
version = "0.1.31"
description = "Some nua_build implementation with Typer"
authors = ["Stefane Fermigier <sf@abilian.com>", "Jerome Dumonteil <jd@abilian.com>"]
license = "AGPL"
readme = "README.md"

[tool.poetry.scripts]
nuad = "nua_build.main:app"

[tool.poetry.dependencies]
python = "^3.10"
toml = "^0.10.2"
wheel = "^0.37.1"
setuptools = "^62.3.2"
psutil = "^5.9.1"
typer = {extras = ["all"], version = "^0.4.1"}
rich = "^12.4.4"
docker = "^5.0.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
isort = "^5.10.1"
black = "^22.3.0"
flake8 = "^4.0.1"
docformatter = "^1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
