[metadata]
id = "flask-pg-via-orch"
version = "1.0"
release = 1
title = "Postgres docker configured via orchestrator"
author = "Nua testers"
tagline = "Postgres docker configured via orchestrator"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "plugin", "PostgreSQL", "docker", "psycopg2"]
license = "MIT"

[build]
document_root = "/nua/app/html"
test = "python -c 'import flask_pg_via_orch'"

[env]
DB_HOST = { from="database", key="hostname" }
DB_PORT = { from="database", key="POSTGRES_PORT" }
USER_DB = { from="database", key="POSTGRES_DB" }
USER_NAME = { from="database", key="POSTGRES_USER" }
USER_PASSWORD = { from="database", key="POSTGRES_PASSWORD" }

[docker]
restart_policy.name = "always"

[port.web]
# publication port of the app inside the container
container = 5000

[[resource]]
# declaration of the required image for the resource, here the official Postgres
# Docker image
name = "database"
type = "postgres"
version = ">=14, <15"
