[metadata]
id = "flask-one-poetry"
version = "1.2"
release = 3
title = "Flask test one poetry auto-detect"
author = "Nua testers"
tagline = "Nua test with Flask - one - poetry auto-detect"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
license = "MIT"

[build]
document-root = "/nua/app/html"

project = "."
start-command = "gunicorn --worker-tmp-dir /dev/shm --workers 2 -b :80 flask_one_poetry.wsgi:app"
test = "python -c 'import flask_one_poetry'"

[docker]
# parameters passed as a dict to docker.run()
auto_remove = true

[port.web]
container = 80
