[metadata]
id = "galene-turn"
version = "0.6.2"
release = 1
title = "Galène videoconference server"
author = "Galene authors"
tagline = "Galène videoconference server"
website = "https://galene.org/"
tags = ["golang", "visio"]
licence = "MIT"
git-url = "https://github.com/jech/galene.git"
git-branch = "galene-0.6-branch"

[build]
packages = ['golang-go', 'git']  # go modules need git for VCS version
build-command = [
    "CGO_ENABLED=0 go build -ldflags='-s -w'",
    "cp galene /nua/app",
    "cp LICENCE /nua/app",
    "cp -a static /nua/app",
    "mkdir /nua/app/groups",
    "mkdir /nua/app/data"
]

[run]
start = """\
/nua/app/galene -http 127.0.0.1:${LISTEN_PORT} \
-insecure \
-turn ${LOCAL_HOST}:${TURN_PORT} -udp-range 49152-65535 \
-groups /nua/app/groups \
-data /nua/app/data"""
# -recordings __DATA_DIR__/recordings  \

[env]
# GALENE_TURN = ""
# GALENE_TURN=1.2.3.4:1194
LOCAL_HOST = { key="hostname" }
TURN_PORT = 8443
LISTEN_PORT = 1194
# GALENE_USER = "galene"
# GALENE_PW = "galene_pw"
DOMAIN = { key="domain" }
# REALM = { key="domain_realm" }
EXTERNAL_IP = { external_ip=true }

[port.web]
container = 8443


[docker]
# network = "host"
restart_policy.name = "always"

# [port.turn]
# container = 1194
# proxy = 1194
# ssl = false

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "bind"
source = "/home/nua/galene/groups"
target = "/nua/app/groups"

[[volume]]
# The mount type (bind / volume / tmpfs / npipe). Default: volume :
type = "bind"
source = "/home/nua/galene/data"
target = "/nua/app/data"
