[metadata]
id = "new-redis-sub-app"
version = "1.0"
release = 1
title = "Redis cache test + sub app"
author = "Nua testers"
tagline = "Redis cache test"
website = "https://nua.rocks/"
tags = ["test", "redis"]

[build]
license = "MIT"
project = "src1"
test = "python -c 'import redis_cache_test'"

[run]
start = "python -c 'from redis_cache_test.app import main; main()'"

[env]
REDIS_HOST = { from="database", key="hostname" }
REDIS_PORT = { from="database", key="REDIS_PORT" }

[port.web]
container = 5000

[[provider]]
# declaration of the required image for the provider: official Redis image
name = "database"
plugin-name = "redis-cache"
plugin-version = ">=7"

[[provider]]
# declaration of the required image for the provider: official Redis image
name = "app2"
type = "app"
network = true
    [provider.build]
    project = "src2"
    test = "python -c 'import echos'"
    [provider.run]
    start = "python -c 'from echos.echo_server import echos; echos(8764, 8765)'"
    [provider.port.one]
    container = 8764
    proxy = 8764
    [provider.port.two]
    container = 8765
    proxy = 8765
