[metadata]
id = "flask-sqla"
version = "1.0"
release = 3
title = "Flask test with sqlalchemy"
author = "Nua testers"
tagline = "Nua test with sqlalchemy"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "plugin", "sqlalchemy"]
license = "MIT"

[build]
document_root = "/nua/app/html"
meta-packages = ["psycopg2"]
project = "."
test = "python -c 'import flask_sqla'"

[docker]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
