[metadata]
id = "echo-two-ports-detect"
version = "1.0"
release = 3
title = "Nua test server 2 ports - toml config - detect project"
author = "Jerome Dumonteil <jd@abilian.com>"
tagline = "Nua test server 2 ports"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
license = "MIT"

[build]

[port.web]
container = 8765

[port.abcd]
container = 8764
proxy = 8764
