#!/usr/bin/env python3

import os
from contextlib import contextmanager
from pathlib import Path

SUB_PACKAGES = [
    "nua-lib",
    "nua-cli",
    "nua-runtime",
    "nua-autobuild",
    "nua-build",
    # "nua-orchestrator",
]


@contextmanager
def chdir(path: str | Path):
    origin = Path().absolute()
    try:
        os.chdir(path)
        yield
    finally:
        os.chdir(origin)


def sh(cmd):
    print(cmd)
    result = os.system(cmd)
    assert result == 0  # noqa: S101


def main():
    sub_packages = SUB_PACKAGES
    if os.getlogin() == "nua":
        sub_packages += ["nua-orchestrator"]

    for sub_package in sub_packages:
        with chdir(sub_package):
           sh("poetry install")
           sh("poetry run pytest --cov nua")

    sh("poetry install")
    sh("poetry run codecov --file */.coverage")


if __name__ == "__main__":
    main()
