[metadata]
id = "flask-sub-folder2"
version = "1.2"
title = "Flask test nua in sub folder"
author = "Nua testers"
tagline = "Nua test with Flask - sub"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
licence = "MIT"
profile = ["test"]
release = 1

[build]
# optional manifest.
# if no manifest, use files in the repository (except dot files)
# - if manifest is not empty, *only* files from manifest are copied
# - "nua-config.toml" is always copied, wether local or not
# manifest = [
# # if no Dockerfile provided => use Nua default Dockerfile:
# "Dockerfile",
# "www",
# "build.py"
# ]

# src_url = "https://github.com/moinwiki/moin/archive/refs/heads/master.tar.gz"
# src_git = "https://github.com/moinwiki/moin.git"

# optional folder containing nua build files if present:
# nua_dir = "nua"  # default to "nua"
nua_dir = "nua_files"
# optional Dockerfile, default is "{nua_dir}/Dockerfile" or "./Dockerfile" if found
# optional build script, default is "{nua_dir}/build.py" or "./build.py" if found
# build_script = ""
# optional start script, default is "{nua_dir}/start.py" or "./start.py" if found
# start_script = ""
# container = "docker"  # default
document_root = "/nua/app/html"

[run]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
