[metadata]
id = "flask-sub-folder2"
version = "1.2"
release = 3
title = "Flask test nua in sub folder"
author = "Nua testers"
tagline = "Nua test with Flask - sub"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
licence = "MIT"

[build]
# optional manifest.
# if no manifest, use files in the repository (except dot files)
# - if manifest is not empty, *only* files from manifest are copied
# - "nua-config.toml" is always copied, wether local or not
# manifest = [
# # if no Dockerfile provided => use Nua default Dockerfile:
# "Dockerfile",
# "www",
# "build.py"
# ]

# src_url = "https://github.com/moinwiki/moin/archive/refs/heads/master.tar.gz"
# src_git = "https://github.com/moinwiki/moin.git"

# optional folder containing nua build files if present:
# nua_dir = "nua"  # default to "nua"
nua_dir = "nua_files"
document-root = "/nua/app/html"
project = "."
test-cmd = "python -c 'import flask_sub_folder2'"

[run]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
