name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev, devel]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu, windows, macos]
        # os: [ubuntu, macos]
        os: [ubuntu]
        # python-version: ['3.10', '3.11']
        python-version: ['3.10']
        action: ["pytest-3.10", "lint"]
        sub_repo: ["nua-lib", "nua-agent", "nua-build", "nua-cli", "nua-orchestrator"]

    env:
        nox_action: ${{ matrix.action }}
        nox_sub_repo: ${{ matrix.sub_repo }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -U pip setuptools wheel nox poetry
      - run: nox -e "${{ matrix.action }}(sub_repo='${{ matrix.sub_repo }}')"
      # - run: codecov
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C079BS4JETT
          # channel: code
          status: FAILED
          color: danger

#  coverage:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: "3.11"
#      - run: pip install -U pip setuptools wheel poetry
#      # - run: ./tools/run-test-with-coverage
#      # Not needed
#      # - run: codecov
