[metadata]
id = "flask-show-port-env"
version = "1.0"
release = 1
title = "Flask show IP, config port via ENV"
author = "Nua testers"
tagline = "Nua test with Flask - IP"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "IP"]

[build]
license = "MIT"
test = "python -c 'import flask_show'"

[run]
# NOTA: start command uses shall explasion variables
start = "gunicorn --worker-tmp-dir /dev/shm --workers 1 -b :${CONT_PORT} flask_show.wsgi:app"

[env]
CONT_PORT = 8000
MY_IP = { external_ip='true' }
STEP1 = "step1"
STEP2 = "step2: dynamic {STEP1}"
STEP3 = "step3: dynamic {STEP2} {CONT_PORT}"
STEP4 = "step4: dynamic {STEP3}"

[docker]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = { key="CONT_PORT" }
