[metadata]
id = "flask-two"
version = "1.2"
release = 2
title = "Flask test two"
author = "Nua testers"
tagline = "Nua test with Flask - two"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static"]
licence = "MIT"

[build]
document-root = "/nua/app/html"
test-cmd = "python -c 'import flask_two'"

[docker]
# parameters passed as a dict to docker run
auto_remove = true
mem_limit = "8G"

[port.web]
container = 80
