[metadata]
id = "flask-sqla"
version = "1.0"
title = "Flask test with sqlalchemy"
author = "Nua testers"
tagline = "Nua test with sqlalchemy"
website = "https://nua.rocks/"
tags = ["test", "html", "web", "static", "plugin", "sqlalchemy"]
licence = "MIT"
profile = ["test"]
release = 1

[build]
document_root = "/nua/app/html"

[run]
# parameters passed as a dict to docker run
auto_remove = true

[port.web]
container = 80
